# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
[tool.black]
enabled = true
line-length = 120
preview = true

[tool.isort]
line_length = 120

[tool.pylint.BASIC]
good-names = ["i",
              "j",
              "k",
              "e",
              "H",
              "W",
              "df",
              "dt",
              "dx",
              "dy",
              "ok",
              "_",
]

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylsp-mypy]
enabled = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# Disable fix for unused imports (`F401`).
unfixable = ["F401"]

